IF OBJECT_ID(N'dbo.Tickets', N'U') IS NULL
CREATE TABLE dbo.Tickets (
    TicketID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    Ticket_DateTime DATETIME NULL,
    Total MONEY NULL CONSTRAINT DF_Tickets_Total DEFAULT 0,
    Taxes MONEY NULL CONSTRAINT DF_Tickets_Taxes DEFAULT 0,
    CustomerID INT NULL CONSTRAINT DF_Tickets_CustomerID DEFAULT 0,
    POSID INT NULL CONSTRAINT DF_Tickets_POSID DEFAULT 0,
    UserID INT NULL CONSTRAINT DF_Tickets_UserID DEFAULT 0,
    Status INT NULL CONSTRAINT DF_Tickets_Status DEFAULT 0
);

IF OBJECT_ID(N'dbo.TicketLines', N'U') IS NULL
CREATE TABLE dbo.TicketLines (
    Line INT NULL CONSTRAINT DF_TicketLines_Line DEFAULT 0,
    Price MONEY NULL CONSTRAINT DF_TicketLines_Price DEFAULT 0,
    Units INT NULL CONSTRAINT DF_TicketLines_Units DEFAULT 0,
    Code INT NULL CONSTRAINT DF_TicketLines_Code DEFAULT 0,
    TicketID INT NULL CONSTRAINT DF_TicketLines_TicketID DEFAULT 0,
    POSID NVARCHAR(50) NULL
);

IF OBJECT_ID(N'dbo.Customers', N'U') IS NULL
CREATE TABLE dbo.Customers (
    CustomerID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    FirstName NVARCHAR(150) NULL,
    LastName NVARCHAR(150) NULL,
    Email NVARCHAR(150) NULL,
    Company NVARCHAR(150) NULL,
    Phone NVARCHAR(150) NULL,
    StreetAddress1 NVARCHAR(150) NULL,
    StreetAddress2 NVARCHAR(150) NULL,
    State NVARCHAR(50) NULL,
    City NVARCHAR(150) NULL,
    ZipCode NVARCHAR(50) NULL,
    County NVARCHAR(100) NULL
);

IF OBJECT_ID(N'dbo.Payments', N'U') IS NULL
CREATE TABLE dbo.Payments (
    PaymentID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    TicketID INT NULL CONSTRAINT DF_Payments_TicketID DEFAULT 0,
    Amount MONEY NULL CONSTRAINT DF_Payments_Amount DEFAULT 0,
    PaymentTypeID INT NULL CONSTRAINT DF_Payments_PaymentTypeID DEFAULT 0,
    PaymentInfo NVARCHAR(150) NULL,
    POSID INT NULL CONSTRAINT DF_Payments_POSID DEFAULT 0
);

IF OBJECT_ID(N'dbo.PaymentTypes', N'U') IS NULL
CREATE TABLE dbo.PaymentTypes (
    PaymentTypeID INT NOT NULL PRIMARY KEY,
    PaymentName NVARCHAR(50) NULL
);

IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
CREATE TABLE dbo.Users (
    UserID INT NOT NULL PRIMARY KEY,
    UserRoleID INT NULL CONSTRAINT DF_Users_UserRoleID DEFAULT 0,
    FirstName NVARCHAR(50) NULL,
    LastName NVARCHAR(50) NULL,
    Password NVARCHAR(50) NULL
);

IF OBJECT_ID(N'dbo.UserRoles', N'U') IS NULL
CREATE TABLE dbo.UserRoles (
    UserRoleID INT NOT NULL PRIMARY KEY,
    UserRoleName NVARCHAR(50) NULL
);

IF OBJECT_ID(N'dbo.POS', N'U') IS NULL
CREATE TABLE dbo.POS (
    POSID INT NOT NULL PRIMARY KEY,
    POSName NVARCHAR(50) NULL,
    Branch NVARCHAR(50) NULL,
    Location NVARCHAR(50) NULL,
    Phone NVARCHAR(50) NULL
);

IF OBJECT_ID(N'dbo.Shifts', N'U') IS NULL
CREATE TABLE dbo.Shifts (
    ShiftID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    StartShift DATETIME NULL,
    EndShift DATETIME NULL,
    StartCash MONEY NULL CONSTRAINT DF_Shifts_StartCash DEFAULT 0,
    EndCash MONEY NULL CONSTRAINT DF_Shifts_EndCash DEFAULT 0,
    POSID INT NULL CONSTRAINT DF_Shifts_POSID DEFAULT 0,
    UserID INT NULL CONSTRAINT DF_Shifts_UserID DEFAULT 0
);

IF OBJECT_ID(N'dbo.Breaks', N'U') IS NULL
CREATE TABLE dbo.Breaks (
    POSID INT NULL CONSTRAINT DF_Breaks_POSID DEFAULT 0,
    BreakID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    ShiftID INT NULL CONSTRAINT DF_Breaks_ShiftID DEFAULT 0,
    StartTime DATETIME NULL,
    EndTime DATETIME NULL
);