name: tailwindtraders-demo
metadata:
  template: tailwindtraders-demo@0.0.1
infra:
  provider: bicep
  path: .
hooks:
  preprovision:
    shell: sh
    run: ./scripts/Preprovision-Azd.sh
  postprovision:
    shell: sh
    run: ./scripts/Postprovision-Azd.sh